### ISSUE TITLE
Request converter from InSpec profile to NIST OSCAL Format

### ISSUE THREAD

**Issue by ejaronne** [mitre/inspec_tools#59] opened 2019-05-09 15:56 UTC

**Comment by aaronlippold** [comment] 2021-09-11 12:26
Given @rbclark work on the ORION project, we may have a better idea of what this request is and if it makes sence. Please discuss.

**Comment by tohch4** [comment] 2021-09-11 20:46
I helped @rbclark with the [inspec-oscal plugin](https://github.com/mitre/inspec-oscal) and I am willing to chip in. Let me know how you can help

**Comment by camdenmoors** [comment] 2022-02-03 19:41
Duplicate of https://github.com/mitre/heimdall2/issues/2403

**Closed by camdenmoors** 2022-02-03 19:41 UTC
Labels: enhancement
